version: '3.8'
services:
  web:
    build: 
      context:  docker-files/web
    image: muhanedyahya/javastack-web
    container_name: javastack-web
    ports:
      - "80:80"
    depends_on:
      - db
      - memcached
      - rabbitmq
      - app
  app:
    build: 
      context: docker-files/app
    image: muhanedyahya/javastack-app
    container_name: app
    ports:
      - "8080:8080"
  db:
    build: 
      context: docker-files/db
    image: muhanedyahya/javastack-db
    container_name: db
    # ports:
    #   - "3306:3306"
  memcached:
    image: memcached:alpine
    container_name: memcached
    # ports:
    #   - "11211:11211"
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    container_name: rabbitmq
    # ports:
    #   - "5672:5672"
